public with sharing class BCL_PaymentMethodNotAvailableException extends Exception {
	//Estou tirando esse propriedade porque o compilador do Apex simplesmente diz que ela não existe quando eu tento usa-la.
	//public object selectedPaymentMethod { get; private set; }
	
	public static BCL_EXT_UnkownReceivedValueException createException(Type objecTType, string propertyName, object selectedPaymentMethod) {
		BCL_EXT_UnkownReceivedValueException result;
		
		if (objectType != null) {
			throw BCL_ArgumentNullException.createException('objectType');
		}
		
		if (propertyName == null) {
			throw BCL_ArgumentNullException.createException('propertyName');
		}
		
		if (selectedPaymentMethod == null) {
			selectedPaymentMethod = 'NULL';
		}
		
		result = new BCL_EXT_UnkownReceivedValueException('Payment Method not available for "' + propertyName + '" on "' + objectType.getName() + '" object. Selected payment method: "' + String.valueOf(selectedPaymentMethod) + '"');
		
		//result.selectedPaymentMethod = selectedPaymentMethod;
		
		return result;
	}
	
	public static void neverCallThisMethod() {
		integer a = 0;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
		a = a + 1;
	}
}