@isTest
private class OpportunityRESTCorpTest {

    static testMethod void myUnitTest() {
    
        /*Opportunity opp = new Opportunity();
        opp.Name = 'Teste';
        opp.Tipo_proposta__c = '1 Locação';
        opp.Tipo_contrato__c = 'ACTRO II';
        opp.AccountId = '0014000001Vri3r' ;
        opp.StageName = 'Abordagem inicial';
        opp.Tipo_de_oportunidade__c = 'LEVE';
        opp.Taxa_de_ades_o__c = 'Não';
        opp.CloseDate = system.today();
        opp.LeadSource = 'Busca Google';
        opp.Origem_Lead_Agrupado__c = 'Busca Google';
        
        insert opp;*/
        
        
    
        OpportunityRESTCorp.neverCallThisMethod();
    }
}