/*
    Classe de testes para Classe controladora da página de Dados de veículos OS e Itens do contrato.
    Criado por: Juliano Szlachta
    Data: 26/06/2018

*/
@isTest
public class Teste_Controller_Dados_Veiculo {
   
    /*
    static testmethod void teste() {
        
        Itens_contrato__c ic = new Itens_contrato__c();
		ic = Controller_Dados_Veiculo.getItem();

		WorkOrder wo = new WorkOrder();
		wo = Controller_Dados_Veiculo.getOS();
        
    }
	*/
}